import {createServer} from 'node:http';
import {MongoClient} from 'mongodb';
import {createBridgeHandler} from './app.mjs';
import {communityIndexes} from './community.mjs';
const {MONGODB_URI,MONGODB_BRIDGE_TOKEN,COMMUNITY_MODERATOR_IDS='',PORT=8080}=process.env;
if(!MONGODB_URI||!MONGODB_BRIDGE_TOKEN||MONGODB_BRIDGE_TOKEN.length<32)throw new Error('Set MONGODB_URI and a random bridge token of at least 32 characters.');
const client=new MongoClient(MONGODB_URI);await client.connect();
const db=client.db('poets_perspectives');await communityIndexes(db);
const server=createServer(createBridgeHandler(db,{token:MONGODB_BRIDGE_TOKEN,moderatorIds:COMMUNITY_MODERATOR_IDS.split(',').map(v=>v.trim()).filter(Boolean)}));
server.listen(Number(PORT));
process.on('SIGTERM',()=>server.close(async()=>{await client.close();process.exit(0)}));
