'use client';
import {useEffect,useRef,useState} from 'react';
import {CloudRain,Cloud,Leaf,Sun,Sparkles,Flower2,Check,Heart} from 'lucide-react';
import {moodLabels,type CheckIn} from '@/lib/checkin';
const feelingOptions=['Anxious','Sad','Calm','Hopeful','Lonely','Overwhelmed','Grateful','Proud','Excited','Irritable','Numb','Content'];
const sections=['Your weather','Body & rest','Mind & self-talk','Connection & care','A final moment'];
const icons=[CloudRain,Cloud,Leaf,Sun,Sparkles];
function Choices({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){
 return <fieldset className="check-question"><legend>{label}</legend><div className="choice-row">{options.map(v=><button type="button" key={v} aria-pressed={value===v} className={'choice '+(value===v?'selected':'')} onClick={()=>onChange(value===v?'':v)}>{v}</button>)}<button type="button" aria-pressed={value===''} className="skip-choice" onClick={()=>onChange('')}>Skip this</button></div></fieldset>
}
export default function DailyCheckin({onComplete,onSkip,onSupport,topics,latest}:{onComplete:(v:CheckIn)=>void;onSkip:()=>void;onSupport:()=>void;topics:string[];latest?:Partial<CheckIn>}){
 const [step,setStep]=useState(0),[form,setForm]=useState<Omit<CheckIn,'id'|'date'>>({mood:null,feelings:[],energy:'',sleep:'',stress:'',focus:'',selfTalk:'',motivation:'',connection:'',body:'',concern:'',need:'',safety:'',reflection:''});
 const title=useRef<HTMLHeadingElement>(null),previousStep=useRef(0);
 useEffect(()=>{if(previousStep.current!==step){title.current?.focus();previousStep.current=step;}},[step]);
 const set=(key:keyof typeof form,value:string)=>setForm(f=>({...f,[key]:value}));
 const needsSupport=form.safety==='I’m not sure'||form.safety==='I need help staying safe';
 return <section className="daily-page"><div className="page-title"><div><span className="eyebrow">BEFORE THE WORLD ASKS ANYTHING OF YOU</span><h1>First, how are you?</h1><p>A little space to notice your day. Every question is optional.</p></div><Flower2 className="check-flower" size={42}/></div><div className="check-layout"><div className="check-sheet"><div className="check-progress" aria-label={`Step ${step+1} of 5`}><span>{String(step+1).padStart(2,'0')} / 05</span><div>{sections.map((s,i)=><span key={s} className={i<=step?'filled':''}/>)}</div><small>{sections[step]}</small></div><h2 tabIndex={-1} ref={title}>{['How is the weather inside you?','What is your body telling you?','How does your mind feel today?','What’s taking up space?','What would you like to carry forward?'][step]}</h2>
{step===0&&<><p className="check-description">You can feel more than one thing. Choose what fits, or leave it open.</p><fieldset className="check-question"><legend>Your overall mood</legend><div className="moods">{moodLabels.map((m,i)=>{const Icon=icons[i];return <button type="button" key={m} aria-pressed={form.mood===i} className={form.mood===i?'selected':''} onClick={()=>setForm(f=>({...f,mood:f.mood===i?null:i}))}><Icon size={29}/>{m}</button>})}</div></fieldset><fieldset className="check-question"><legend>What feelings are here? <small>Choose as many as you like.</small></legend><div className="choice-row">{feelingOptions.map(f=><button key={f} className={'choice '+(form.feelings.includes(f)?'selected':'')} aria-pressed={form.feelings.includes(f)} onClick={()=>setForm(v=>({...v,feelings:v.feelings.includes(f)?v.feelings.filter(x=>x!==f):[...v.feelings,f]}))}>{f}</button>)}</div></fieldset></>}
{step===1&&<><Choices label="How much energy do you have?" value={form.energy} options={['Low','Steady','High']} onChange={v=>set('energy',v)}/><Choices label="How did you sleep?" value={form.sleep} options={['Rested','Some rest','Very little sleep']} onChange={v=>set('sleep',v)}/><Choices label="What do you notice in your body?" value={form.body} options={['Comfortable','Tense','Restless','Tired','Hard to tell']} onChange={v=>set('body',v)}/></>}
{step===2&&<><Choices label="How much stress are you carrying?" value={form.stress} options={['Little or none','Manageable','High','Overwhelming']} onChange={v=>set('stress',v)}/><Choices label="How is your attention?" value={form.focus} options={['Clear','Scattered','Racing thoughts','Foggy']} onChange={v=>set('focus',v)}/><Choices label="How have you been speaking to yourself?" value={form.selfTalk} options={['Kindly','Neutrally','Somewhat critical','Very critical']} onChange={v=>set('selfTalk',v)}/><Choices label="How does starting things feel?" value={form.motivation} options={['Hard to begin','One small step feels possible','Ready to engage']} onChange={v=>set('motivation',v)}/></>}
{step===3&&<><Choices label="How connected do you feel to others?" value={form.connection} options={['Supported','Somewhat connected','Distant','Isolated']} onChange={v=>set('connection',v)}/><label className="check-question">What would you like to focus on?<select value={form.concern} onChange={e=>set('concern',e.target.value)}><option value="">Nothing specific / skip</option>{topics.map(t=><option key={t}>{t}</option>)}</select></label><Choices label="What would feel most supportive?" value={form.need} options={['A little direction','Rest','Connection','Room to celebrate','Space to express myself']} onChange={v=>set('need',v)}/></>}
{step===4&&<><label className="check-question">Anything you want the page to hold?<textarea value={form.reflection} rows={3} maxLength={2000} onChange={e=>set('reflection',e.target.value)} placeholder="A worry, a small joy, a hope for today…"/><small>Optional · kept with this check-in.</small></label><Choices label="Do you feel able to keep yourself safe right now?" value={form.safety} options={['I feel safe','I’m not sure','I need help staying safe']} onChange={v=>set('safety',v)}/>{needsSupport&&<div className="notice support-notice"><Heart size={20}/><div><p>You deserve support right now. If you cannot stay safe, call emergency services or go to the nearest emergency department. If possible, stay near someone you trust.</p><button className="primary" onClick={onSupport}>Find support now</button></div></div>}{form.energy==='High'&&form.sleep==='Very little sleep'&&<p className="notice">High energy with very little sleep can be worth discussing with a professional, especially if unusual for you or paired with risky impulses.</p>}<p className="check-description">Your answers guide gentle suggestions, not a diagnosis or a safety assessment. There is no score to pass.</p></>}
<div className="check-actions">{step>0?<button className="secondary" onClick={()=>setStep(s=>s-1)}>Back</button>:<button className="text-button" onClick={onSkip}>Maybe later</button>}<button className="primary" onClick={()=>step<4?setStep(s=>s+1):onComplete({...form,id:crypto.randomUUID(),date:new Date().toISOString()})}>{step<4?'Continue':needsSupport?'Save check-in & find support':'Save my check-in'}</button></div></div><aside className="check-margin"><img src="/garden.png" alt="A quiet painted garden"/><div><span className="eyebrow">A NOTE IN THE MARGIN</span><h3>You are allowed<br/>to arrive as you are.</h3><p>There is room for the messy, the hopeful, the tired, and the joyful. None of it makes you less you.</p><div className="check-margin-rule"/><small>About 3–5 minutes. Skip any question, or come back when you’re ready.</small>{latest&&<p className="last-check"><Check size={15}/> Last check-in: {new Date(latest.date!).toLocaleDateString()}</p>}</div></aside></div></section>
}
