'use client';
import {useEffect,useRef,useState} from 'react';
import {Bookmark,BookOpen,Feather,Search,Sparkles,X,Check} from 'lucide-react';
import {readings,inspiriaTags,filterReadings,readingPage,scrapbookText,type Reading} from '@/lib/inspiria';
export default function Inspiria({onSave,entries}:{onSave:(title:string,body:string)=>void;entries:{body:string}[]}){
 const [query,setQuery]=useState(''),[kind,setKind]=useState('All'),[tags,setTags]=useState<string[]>([]),[selected,setSelected]=useState<Reading|null>(null),[page,setPage]=useState(0);
 const dialog=useRef<HTMLDialogElement>(null);
 const filtered=filterReadings(query,kind,tags);
 const batch=readingPage(filtered,page),shelf=useRef<HTMLDivElement>(null);
 function turnPage(next:number){setPage(next);shelf.current?.scrollIntoView({block:"start",behavior:"instant"});shelf.current?.focus({preventScroll:true});}
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close()},[selected]);
 function toggleTag(tag:string){setPage(0);setTags(t=>t.includes(tag)?t.filter(v=>v!==tag):[...t,tag]);}
 function reset(){setPage(0);setQuery('');setKind('All');setTags([])}
 function saved(r:Reading){return entries.some(e=>e.body===scrapbookText(r))}
 return <section className="inspiria"><div className="inspiria-heading"><div><span className="eyebrow">A LITTLE ANTHOLOGY FOR YOUR INNER WORLD</span><h1>Inspiria<span>words to wander through.</span></h1><p>For a feeling you can name, or one you haven’t found words for yet.</p></div><button className="secondary" onClick={()=>setSelected(readings[Math.floor(Math.random()*readings.length)])}><Sparkles size={17}/> Find me a little wonder</button></div><div className="inspiria-controls"><div className="inspiria-search"><Search size={19}/><input value={query} onChange={e=>{setPage(0);setQuery(e.target.value)}} placeholder="Search words, titles, poets, or feelings…" aria-label="Search Inspiria"/>{query&&<button aria-label="Clear search" onClick={()=>{setPage(0);setQuery('')}}><X size={17}/></button>}</div><div className="type-filters" aria-label="Filter by format">{['All','Poem','Quote'].map(k=><button key={k} aria-pressed={kind===k} className={kind===k?'selected':''} onClick={()=>{setPage(0);setKind(k)}}>{k==='All'?'All words':k==='Poem'?'Poems':'Quotes'}</button>)}</div></div><div className="tag-intro"><span>Browse by feeling</span><small>Select one or more themes</small></div><div className="inspiria-tags" aria-label="Filter by theme">{inspiriaTags.map(t=><button key={t} className={tags.includes(t)?'selected':''} aria-pressed={tags.includes(t)} onClick={()=>toggleTag(t)}>{tags.includes(t)&&<Check size={12}/>} {t}</button>)}</div><div className="results-line" ref={shelf} tabIndex={-1}><p role="status">Showing {batch.start}–{batch.end} of {filtered.length} pieces{tags.length?' · matching all selected themes':''}</p>{(query||tags.length>0||kind!=='All')&&<button className="text-button" onClick={reset}>Clear all filters</button>}</div>
{filtered.length?<div className="inspiria-grid">{batch.items.map((r,i)=><article key={r.id} className={'reading-card reading-tone-'+i%3}><div className="reading-meta">{r.type==='Poem'?<Feather size={16}/>:<BookOpen size={16}/>}<span>{r.type} · {r.original?'Original':'Literary collection'}</span></div><button className="open-reading" onClick={()=>setSelected(r)} aria-label={`Read ${r.title} by ${r.author}`}><h2>{r.title}</h2><p className={r.type==='Poem'?'poem-excerpt':'quote-excerpt'}>{r.type==='Poem'?r.body.slice(0,240).split('\n').slice(0,4).join('\n')+(r.body.length>240||r.body.split('\n').length>4?'…':''):`“${r.body}”`}</p></button><div className="reading-credit">{r.author}<small>{r.work}</small></div><div className="card-tags">{r.tags.map(t=><button key={t} onClick={()=>toggleTag(t)} aria-pressed={tags.includes(t)} className={tags.includes(t)?'selected':''}>{t}</button>)}</div><div className="reading-actions"><button className="text-button" onClick={()=>setSelected(r)}>Read {r.type==='Poem'?'poem':'quote'}</button><button className="save-reading" aria-label={saved(r)?`${r.title} is saved`:`Save ${r.title} to scrapbook`} disabled={saved(r)} onClick={()=>onSave(r.title,scrapbookText(r))}>{saved(r)?<Check size={17}/>:<Bookmark size={17}/>} {saved(r)?'Kept':'Keep'}</button></div></article>)}</div>:<div className="empty"><BookOpen size={35}/><h2>No words on this shelf just yet.</h2><p>Try a different phrase, or remove a theme to open up the collection.</p><button className="primary" onClick={reset}>Show the whole collection</button></div>}
{filtered.length>0&&<div className="anthology-pagination" aria-label="Inspiria pages"><button className="secondary" disabled={batch.page===0} onClick={()=>turnPage(batch.page-1)}>Previous 50</button><span>Page {batch.page+1} of {batch.pages}</span>{batch.page<batch.pages-1?<button className="primary" onClick={()=>turnPage(batch.page+1)}>Go Deeper</button>:<span className="last-page-note">You’ve reached the last page.</span>}</div>}
<p className="inspiria-credit">Original poems and reflections are written for Poets & Perspectives. The 1,000-piece collection includes public-domain writing by Rabindranath Tagore and Emily Dickinson, with themes including nature, love, spirituality, and loss. Every literary piece keeps its author and source; early editions may use different punctuation. Keep anything that speaks to you in your scrapbook. <a href="/credits/gutenberg-license.txt" target="_blank" rel="noreferrer">Text source license</a>.</p>
<dialog ref={dialog} className="inspiria-dialog" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}} aria-labelledby="reading-title"><div className="reading-detail">{selected&&<><button className="close" aria-label="Close reading" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">INSPIRIA · {selected.type.toUpperCase()}</span><h2 id="reading-title">{selected.title}</h2><p className="detail-author">{selected.author}</p><div className={'full-reading '+(selected.type==='Quote'?'full-quote':'')}>{selected.type==='Quote'?`“${selected.body}”`:selected.body}</div><p className="detail-work">{selected.work}</p>{selected.source&&<a className="text-button" target="_blank" rel="noreferrer" href={selected.source}>Read the source text</a>}<div className="card-tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><button className="primary" disabled={saved(selected)} onClick={()=>onSave(selected.title,scrapbookText(selected))}>{saved(selected)?<Check size={17}/>:<Bookmark size={17}/>} {saved(selected)?'Kept in your scrapbook':'Keep in my scrapbook'}</button></>}</div></dialog></section>
}
