'use client';
import {useEffect,useState,useRef} from 'react';
import DailyCheckin from '@/components/poets/DailyCheckin';
import Inspiria from '@/components/poets/Inspiria';
import ChapterDetails from '@/components/poets/ChapterDetails';
import {topics} from '@/lib/chapters';
import {makeIntentions,type CheckIn} from '@/lib/checkin';
import {Sun,BookOpen,Feather,Heart,Flower2,Leaf,Music,Plus,X,Check,Bell,ShieldCheck,Settings,Wind,Bookmark,Phone,ChevronRight,Smile,Cloud,CloudRain,Sparkles,Users,Menu} from 'lucide-react';
const moods=['Heavy','Unsettled','In-between','At ease','Radiant'];
const moodIcons=[CloudRain,Cloud,Leaf,Sun,Sparkles];
const quotes=[['“I dwell in Possibility —”','Emily Dickinson','Poem 466'],['“The world is so full of a number of things, / I’m sure we should all be as happy as kings.”','Robert Louis Stevenson','A Child’s Garden of Verses'],['“A thing of beauty is a joy for ever.”','John Keats','Endymion']];
const initial={profile:{name:'',age:'',status:'',history:'',concerns:'',interests:'',goals:'',working:'',spiritual:'Secular'},entries:[] as any[],checks:[] as any[],people:[] as any[],done:[] as string[]};
export default function Home(){
const saveQueue=useRef(Promise.resolve());
const [tab,setTab]=useState('Daily check-in'),[data,setData]=useState(initial),[modal,setModal]=useState(''),[concern,setConcern]=useState('Stress'),[note,setNote]=useState(''),[title,setTitle]=useState(''),[quote,setQuote]=useState(0),[toast,setToast]=useState(''),[local,setLocal]=useState(false),[cloud,setCloud]=useState(false),[ready,setReady]=useState(false),[breath,setBreath]=useState(false),[seconds,setSeconds]=useState(60),[notify,setNotify]=useState(false),[person,setPerson]=useState(''),[phone,setPhone]=useState(''),[search,setSearch]=useState(''),[selectedCheck,setSelectedCheck]=useState<any>(null);
useEffect(()=>{try{const saved=localStorage.getItem('pp-device');if(saved){setData(JSON.parse(saved));setLocal(true);}}catch{} fetch('/api/state').then(r=>r.ok?r.json():null).then((v:any)=>{if(v?.state){setData(v.state);setCloud(true);}else if(v?.connected)setCloud(true);}).catch(()=>setToast('Cloud storage is unavailable; this is a session-only preview.')).finally(()=>setReady(true));},[]);
useEffect(()=>{if(!ready)return;if(local){try{localStorage.setItem('pp-device',JSON.stringify(data));}catch{setToast('Device saving failed. Export your scrapbook to keep it.');}}if(cloud){const snapshot=JSON.stringify({state:data});const timer=setTimeout(()=>{saveQueue.current=saveQueue.current.then(async()=>{try{const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:snapshot});if(!r.ok)throw new Error();}catch{setToast('Cloud save failed. Please export your pages before leaving.');}});},400);return()=>clearTimeout(timer);}},[data,local,ready,cloud]);
useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const t=setTimeout(()=>{(document.querySelector('.modal button, .modal input') as HTMLElement)?.focus()},30);const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setModal('');setBreath(false);}if(e.key==='Tab'){const elements=Array.from(document.querySelectorAll<HTMLElement>('.modal button:not(:disabled),.modal input,.modal textarea,.modal select,.modal a[href]'));const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{clearTimeout(t);document.removeEventListener('keydown',handler);previous?.focus()}},[modal]);
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
useEffect(()=>{if(!breath)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){setBreath(false);return 60;}return s-1}),1000);return()=>clearInterval(t)},[breath]);
useEffect(()=>{if(!notify)return;const t=setInterval(()=>{const text='A small pause belongs to you. Unclench your shoulders and look toward the light.';setToast(text);if(Notification.permission==='granted')new Notification('A gentle note',{body:text});},1800000);return()=>clearInterval(t)},[notify]);
const latest=data.checks[0],activeMood=latest?.mood??2;
const intentions=makeIntentions(latest),plans=intentions.map(i=>i.text);
function saveEntry(t:string,b:string){if(!b.trim())return;setData(d=>({...d,entries:[{id:crypto.randomUUID(),title:t||'A little piece of today',body:b,date:new Date().toISOString()},...d.entries]}));setModal('');setNote('');setTitle('');setToast('A little piece of you, tucked away.');}
function finish(check:CheckIn){setData(d=>({...d,checks:[check,...d.checks],done:[]}));setTab('My sanctuary');if(check.safety==='I’m not sure'||check.safety==='I need help staying safe')setModal('support');setToast('Your check-in is saved with your pages.');}
function checkin(){setTab('Daily check-in');setModal('');}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='poets-and-perspectives.json';a.click();URL.revokeObjectURL(a.href)}
return <div className={'app mood-'+activeMood}><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('My sanctuary')}}><Feather size={30}/><span>Poets &<br/><i>Perspectives</i></span></a><div className="brand-note">A LITTLE SPACE TO BE HUMAN</div><div className="nav-label">YOUR INNER WORLD</div><nav>{[['Daily check-in',Flower2],['My sanctuary',Sun],['My scrapbook',BookOpen],['Inspiria',Sparkles],['The reading room',Bookmark],['My people',Heart],['My story',Feather]].map(([name,Icon]:any)=><button key={name} className={tab===name?'active':''} onClick={()=>name==='Daily check-in'?checkin():setTab(name)}><Icon size={19}/>{name}{tab===name&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="side-quote"><Leaf size={26}/><p>“And still, I rise.”</p><small>A reminder in your own words:<br/>there is room to begin again.</small></div><button onClick={()=>setModal('support')} className="support"><Heart size={17}/> I need a little support</button><button onClick={()=>setModal('settings')} className="settings"><Settings size={17}/> Preferences & privacy</button><div className="user"><span className="avatar">{data.profile.name?.[0]||'Y'}</span><div>{data.profile.name||'Your little corner'}<small>{cloud?'Private cloud saving':local?'Saved on this device':'Private session · not saved'}</small></div></div></div></aside>
<main><header><div className="breadcrumb">YOUR SANCTUARY <span>/</span> {tab==='My sanctuary'?'A NEW PAGE':tab.toUpperCase()}</div><div className="header-right"><span><Leaf size={15}/> Go at your own pace</span><button aria-label="Gentle reminders" onClick={()=>setModal('settings')}><Bell size={19}/></button><button className="avatar" aria-label="My story" onClick={()=>setTab('My story')}>{data.profile.name?.[0]||'Y'}</button></div></header>
<div className="content"><div className="date-line"><span>{new Date().toLocaleDateString('en-IN',{weekday:'long',month:'long',day:'numeric'})}</span><span>✦ &nbsp; EVERY SEASON OF YOU BELONGS HERE</span></div>
{tab==='Daily check-in'&&<DailyCheckin topics={Object.keys(topics)} latest={latest} onComplete={finish} onSkip={()=>setTab('My sanctuary')} onSupport={()=>setModal('support')}/>}
{tab==='Inspiria'&&<Inspiria onSave={saveEntry} entries={data.entries}/>}
{tab==='My sanctuary'&&<><div className="welcome"><h1>A softer place to land{data.profile.name?`, ${data.profile.name}`:'.'}</h1><p>You don’t have to have it all figured out. Let’s begin with how you feel.</p></div><section className="hero"><div className="hero-copy"><div className="eyebrow">YOUR DAILY MOMENT OF CARE</div><h2>How is the weather<br/><i>inside you today?</i></h2><p>No right answers. No fixing required.<br/>Just a small moment to listen to yourself.</p><button className="primary" onClick={checkin}><Sun size={17}/> {latest?'Check in again':'Let’s check in'}</button><small>3–5 minutes · just for you</small></div><div className="hero-art"><img src="/garden.png" alt="An oil-painted garden with roses, cypress trees and sunlit hills"/><div className="art-caption">a gentler kind of growing</div></div></section>
<div className="section-heading"><div><span className="eyebrow">LITTLE THINGS, LOVINGLY CHOSEN</span><h2>{latest?'Your rhythm for today':'A little care for today'}</h2></div><span className="pill"><Flower2 size={14}/> {latest?(latest.mood==null?'Your own pace':moods[activeMood]):'Begin wherever you are'}</span></div><div className="care-grid"><article className="care-card breathe"><span className="card-icon"><Wind/></span><span className="mini">COME BACK TO YOURSELF</span><h3>A moment of stillness</h3><p>Let the world wait. Feel your feet on the ground and settle into this moment.</p><button onClick={()=>{setModal('breathe');setSeconds(60)}}>Take a gentle pause <ChevronRight size={16}/></button><small>1 MINUTE · GROUNDING</small></article><article className="care-card music"><span className="card-icon"><Music/></span><span className="mini">A SOUNDTRACK FOR YOUR SOUL</span><h3>{activeMood===4?'Room for your joy':'Let the music hold you'}</h3><p>{activeMood===4?'Warm, uplifting sounds for a day worth celebrating.':'Soft piano, quiet strings, and a little room to breathe.'}</p><a href={'https://open.spotify.com/search/'+encodeURIComponent(activeMood===4?'uplifting acoustic':'peaceful piano')} target="_blank" rel="noreferrer">Find your soundtrack <ChevronRight size={16}/></a><small>OPENS SPOTIFY · YOUR CHOICE</small></article><article className="care-card connect"><span className="card-icon"><Heart/></span><span className="mini">YOU DON’T HAVE TO DO IT ALONE</span><h3>A familiar voice</h3><p>A small hello can make the distance feel smaller. Who’s on your mind?</p><button onClick={()=>setTab('My people')}>Reach out to your people <ChevronRight size={16}/></button><small>A LITTLE CONNECTION</small></article></div>
<div className="lower-grid"><section className="quote-card"><div className="eyebrow"><BookOpen size={15}/> WORDS TO KEEP CLOSE <button aria-label="Another quote" onClick={()=>setQuote((quote+1)%quotes.length)}>↻</button></div><blockquote>{quotes[quote][0]}</blockquote><p>{quotes[quote][1]} <span>— {quotes[quote][2]}</span></p><button className="text-button" onClick={()=>saveEntry('Words to keep close',quotes[quote].join('\n'))}><Bookmark size={15}/> Keep in my scrapbook</button></section><section className="today-list"><div className="eyebrow">YOUR GENTLE INTENTIONS</div><h3>Small is still something.</h3>{plans.map((p,i)=><label key={p}><input type="checkbox" checked={data.done.includes(p)} onChange={()=>{if(!latest&&i===0){checkin();return;}setData(d=>({...d,done:d.done.includes(p)?d.done.filter(v=>v!==p):[...d.done,p]}))}}/><span>{p}{latest&&<small>{intentions[i].reason}</small>}</span></label>)}{latest&&<small>Chosen from what you shared. Suggestions, not a diagnosis.</small>}</section></div><button className="journal-invite" onClick={()=>setModal('entry')}><Feather/><span>Something on your mind?<small>Leave a thought on the page. It doesn’t have to be beautiful.</small></span><Plus/></button></>}
{tab==='My scrapbook'&&<><div className="page-title"><div><span className="eyebrow">THE PIECES THAT MAKE YOU, YOU</span><h1>My scrapbook</h1><p>Thoughts, borrowed words, and ordinary little wonders.</p></div><button className="primary" onClick={()=>setModal('entry')}><Plus size={17}/> Add a page</button></div>{!data.entries.length?<div className="empty"><Feather size={40}/><h2>Your first page is waiting.</h2><p>A sentence is enough. What would you like to remember?</p><button className="primary" onClick={()=>setModal('entry')}>Write something</button></div>:<div className="entries">{data.entries.map(e=><article key={e.id}><small>{new Date(e.date).toLocaleDateString()}</small><h2>{e.title}</h2><p>{e.body}</p><button className="text-button" onClick={()=>{setData(d=>({...d,entries:d.entries.filter(v=>v.id!==e.id)}));setToast('Page removed.')}}>Remove page</button></article>)}</div>}<h2 className="history-title">The seasons you’ve felt</h2><div className="history">{data.checks.length?data.checks.slice(0,14).map(c=><button className="history-check" key={c.id} onClick={()=>{setSelectedCheck(c);setModal('checkdetail')}}><Flower2/><strong>{c.mood==null?'Not shared':moods[c.mood]}</strong><small>{new Date(c.date).toLocaleDateString()}</small><span>View reflection</span></button>):<p>Your check-ins will appear here. No scores to chase.</p>}</div></>}
{tab==='The reading room'&&<><div className="page-title"><div><span className="eyebrow">WISDOM, WITHOUT THE SHOULDERS OF “SHOULD”</span><h1>The reading room</h1><p>Fifteen chapters of practical care, with articles and videos to explore at your pace.</p></div></div><input className="search" placeholder="Find a feeling…" aria-label="Search feelings" value={search} onChange={e=>setSearch(e.target.value)}/><div className="reading-grid">{Object.keys(topics).filter(t=>t.toLowerCase().includes(search.toLowerCase())).map((t,i)=><button key={t} onClick={()=>{setConcern(t);setModal('reading')}}><span className="chapter">CHAPTER {String(i+1).padStart(2,'0')}</span><h2>{t}</h2><p>{topics[t][0]}</p><span className="text-button">Open a little perspective <ChevronRight size={15}/></span></button>)}</div>{!Object.keys(topics).some(t=>t.toLowerCase().includes(search.toLowerCase()))&&<p>No matching chapter. Try “stress” or “love”.</p>}<section className="spiritual"><Leaf/><div><h2>A dharma for the everyday</h2><p>{data.profile.spiritual==='Secular'?'Choose a spiritual lens in My story if you would like reflections from dharmic traditions. Your practical care stays available either way.':data.profile.spiritual==='Gita-inspired'?'A reflection inspired by Bhagavad Gita 2.47: offer care to the action you can take, while loosening your grip on its outcome. This is an interpretation, not a clinical treatment.':'A Buddhist-inspired reflection: notice that feelings change. Meet this moment with compassion, without making it your whole identity. This is a reflection, not a clinical treatment.'}</p></div></section><p className="sources">Care references: <a href="https://www.who.int/publications/i/item/9789240003927" target="_blank" rel="noreferrer">WHO · Doing What Matters in Times of Stress</a> · <a href="https://www.who.int/news-room/fact-sheets/detail/depression" target="_blank" rel="noreferrer">Understanding depression</a>. This small library is educational, not exhaustive or a substitute for professional care.</p></>}
{tab==='My people'&&<><div className="page-title"><div><span className="eyebrow">THE THREADS THAT KEEP US CLOSE</span><h1>My people</h1><p>Keep a little room for the people who feel safe.</p></div><button className="primary" onClick={()=>setModal('person')}><Plus size={17}/> Add someone</button></div><div className="people-grid">{data.people.map(p=><article className="person" key={p.id}><span className="avatar">{p.name[0]}</span><h2>{p.name}</h2><p>{p.phone||'A little hello is enough.'}</p>{p.phone&&<a className="primary" href={'tel:'+p.phone}><Phone size={16}/> Call</a>}<button className="text-button" onClick={()=>saveEntry('A moment of connection',`I made time to connect with ${p.name} today.`)}>Record a connection</button><button className="text-button" onClick={()=>setData(d=>({...d,people:d.people.filter(v=>v.id!==p.id)}))}>Remove</button></article>)}</div>{!data.people.length&&<div className="empty"><Users size={40}/><h2>Connection starts with one name.</h2><p>Add someone you trust. We never contact them automatically.</p><button className="primary" onClick={()=>setModal('person')}>Add a loved one</button></div>}</>}
{tab==='My story'&&<><div className="page-title"><div><span className="eyebrow">MORE THAN A MOOD, MORE THAN A MOMENT</span><h1>My story</h1><p>Share only what feels right. Every field is optional.</p></div></div><div className="profile-form">{[['name','What should we call you?'],['age','Age'],['status','Your current season / relationship status'],['interests','Things that bring you alive'],['working','What you’re working on'],['goals','Your hopes and goals'],['history','History you want to keep in mind'],['concerns','What you think you may be experiencing']].map(([key,label])=><label key={key}>{label}{['history','concerns','goals'].includes(key)?<textarea maxLength={5000} value={(data.profile as any)[key]} onChange={e=>setData(d=>({...d,profile:{...d.profile,[key]:e.target.value}}))}/>:<input maxLength={500} type={key==='age'?'number':'text'} min={0} max={120} value={(data.profile as any)[key]} onChange={e=>setData(d=>({...d,profile:{...d.profile,[key]:e.target.value}}))}/>}</label>)}<label>Your preferred lens<select value={data.profile.spiritual} onChange={e=>setData(d=>({...d,profile:{...d.profile,spiritual:e.target.value}}))}><option>Secular</option><option>Gita-inspired</option><option>Buddhist-inspired</option></select></label><div className="profile-note"><ShieldCheck/><p>{cloud?'Your changes are saved privately in your connected database.':local?'Changes are saved on this device. Anyone using this browser profile may be able to read them.':'Changes stay in this session until you enable device saving or connect cloud storage.'} Personal history is a journal, not evidence of a diagnosis. Suggestions use your check-in answers and chosen spiritual lens.</p><button className="text-button" onClick={()=>setModal('settings')}>Manage saving</button></div></div></>}
<footer><span><Feather size={14}/> Made for the beautifully unfinished.</span><span>Supportive reflections, never a diagnosis. <button onClick={()=>setModal('support')}>Find support</button></span></footer></div></main>
{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
{modal&&<div className="overlay" onClick={e=>{if(e.target===e.currentTarget){setModal('');setBreath(false)}}}><section className={"modal "+(modal==='reading'?'chapter-modal':'')} role="dialog" aria-modal="true" aria-label={modal}><button className="close" aria-label="Close" onClick={()=>{setModal('');setBreath(false)}}><X/></button>
{modal==='checkdetail'&&selectedCheck&&<><span className="eyebrow">YOUR CHECK-IN · {new Date(selectedCheck.date).toLocaleDateString()}</span><h2>A moment you noticed.</h2><dl className="check-summary">{[['Mood',selectedCheck.mood==null?'Not shared':moods[selectedCheck.mood]],['Feelings',selectedCheck.feelings?.join(', ')],['Energy',selectedCheck.energy],['Sleep',selectedCheck.sleep],['Body',selectedCheck.body],['Stress',selectedCheck.stress],['Focus',selectedCheck.focus],['Self-talk',selectedCheck.selfTalk],['Motivation',selectedCheck.motivation],['Connection',selectedCheck.connection],['Focus for care',selectedCheck.concern],['Support wanted',selectedCheck.need],['Safety',selectedCheck.safety]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not shared'}</dd></div>)}</dl>{selectedCheck.reflection&&<blockquote className="check-reflection">{selectedCheck.reflection}</blockquote>}<small>Your own observations, not a diagnosis.</small></>}
{modal==='entry'&&<><span className="eyebrow">A PAGE OF YOUR OWN</span><h2>Let the page hold it.</h2><label>A little title<input maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Something I want to remember"/></label><label>Your words<textarea autoFocus rows={7} maxLength={15000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Today, I noticed…"/></label><button className="primary" disabled={!note.trim()} onClick={()=>saveEntry(title,note)}>Tuck this page away</button></>}
{modal==='person'&&<><h2>Someone who feels safe.</h2><label>Name<input value={person} maxLength={100} onChange={e=>setPerson(e.target.value)}/></label><label>Phone number (optional)<input type="tel" value={phone} onChange={e=>setPhone(e.target.value.replace(/[^+\d ()-]/g,''))}/></label><p>Stored with your scrapbook. Never messaged automatically.</p><button className="primary" disabled={!person.trim()} onClick={()=>{setData(d=>({...d,people:[...d.people,{id:crypto.randomUUID(),name:person,phone}]}));setPerson('');setPhone('');setModal('')}}>Keep them close</button></>}
{modal==='breathe'&&<><span className="eyebrow">NOTHING TO ACHIEVE HERE</span><h2>Arrive in this moment.</h2><div className={'breathing '+(breath?'moving':'')}><Wind size={36}/><span>{breath?seconds+' seconds':'One minute'}</span></div><p>Feel your feet supported. Notice three things you can see, two sounds, and one physical sensation. Breathe naturally; there is no need to hold your breath.</p><button className="primary" onClick={()=>setBreath(!breath)}>{breath?'Pause':'Begin a gentle minute'}</button><small>Stop whenever you like if this doesn’t feel comfortable.</small></>}
{modal==='reading'&&<ChapterDetails title={concern} onWrite={(t,p)=>{setTitle(t+' · a reflection');setNote(p+'\n\n');setModal('entry')}} onSupport={()=>setModal('support')}/>}
{modal==='support'&&<><Heart className="support-heart"/><h2>You don’t have to hold this alone.</h2><p>If you might act on thoughts of harming yourself or cannot stay safe, contact emergency services or go to the nearest emergency department. If possible, stay near a trusted person and move away from things you could use to hurt yourself.</p><a className="primary" href="tel:112">India emergency · 112</a><a className="option" href="tel:14416">Talk to Tele-MANAS · 14416</a><p>For mental health support in India. Outside India, use your local emergency number or <a href="https://findahelpline.com" target="_blank" rel="noreferrer">find a local helpline</a>.</p><button className="text-button" onClick={()=>{setModal('');setTab('My people')}}>Find a trusted person in my circle</button><p className="sources">This app is not monitored and cannot dispatch help. <a href="https://dghs.mohfw.gov.in/national-mental-health-programme.php" target="_blank" rel="noreferrer">Tele-MANAS information</a></p></>}
{modal==='settings'&&<><span className="eyebrow">YOUR SPACE, YOUR CHOICES</span><h2>Care includes privacy.</h2><div className="notice">{cloud?'MongoDB connection active.':'MongoDB is not connected. You are using a session-only preview unless you choose device saving below.'}</div><label className="toggle"><input type="checkbox" checked={local} onChange={e=>{setLocal(e.target.checked);if(!e.target.checked)localStorage.removeItem('pp-device')}}/> Save my scrapbook on this device</label><p>Device storage is not encrypted. Avoid it on a shared device. You can export or erase your pages below.</p><label className="toggle"><input type="checkbox" checked={notify} onChange={async e=>{if(!e.target.checked){setNotify(false);return;}if(!('Notification' in window)){setToast('This browser does not support notifications.');return;}const permission=await Notification.requestPermission();if(permission==='granted'){setNotify(true);setToast('Gentle reminders are on while this page is open.')}else setToast('Notifications were not enabled. You can change browser permissions.')}}/> Gentle reminders every 30 minutes</label><p>Optional reminders work while this page is open. Closed-app push reminders are not connected yet.</p><button className="option" onClick={exportData}>Export my scrapbook (JSON)</button><button className="option" onClick={()=>setModal('erase')}>Erase my personal data</button></>}
{modal==='erase'&&<><h2>Clear your pages?</h2><p>This removes your profile, check-ins, people and scrapbook entries from this session, enabled device storage and connected cloud storage. Export a copy first if you want to keep them.</p><button className="primary" onClick={()=>{setData(initial);localStorage.removeItem('pp-device');setModal('');setToast('Your pages have been cleared.')}}>Erase my data</button></>}
</section></div>}
</div>}
